### ISSUE TITLE
[Feature] Add support for Schwab

### ISSUE THREAD

**Issue by arsaboo** [edtechre/pybroker#117]
Can we add support for Schwab API - https://github.com/alexgolec/schwab-py

**Comment by edtechre** [comment]
Thank you for the suggestion @arsaboo, I will look into adding this,

**Comment by edtechre** [comment]
Hi @arsaboo,

On further consideration, I won't be adding support for a Schwab data source. This is because I want to keep dependencies to a minimum, where YF and Alpaca are available primarily as examples to get people started. 

Instead, you can simply query to the Schwab API and then use the returned DataFrame as a data source. See https://www.pybroker.com/en/latest/notebooks/7.%20Creating%20a%20Custom%20Data%20Source.html#Using-a-Pandas-DataFrame.
