### ISSUE TITLE
Take Profit / Stop Loss question

### ISSUE THREAD

**Issue by tsunamilx** [edtechre/pybroker#160]
Hi

I am trying the take profit / stop loss method, I set stop loss to 3%, and take profit to 10%, and I see some records that are stopped at the price way lower/higher than expected. I am trading on a crypto asset so there should be no gap between bars.

For example:

this is 1h chart
![image](https://github.com/user-attachments/assets/7b11aec7-701e-42de-9758-6b2551a1287c)

My entry signal appears at b1 (time is 07:00) close (value is 1.11) (the worst entry signal ever LOL), I set fill price to be b1 close, the trade executes at b2 (08:00), to my understanding it should stop at some where near 1.07 on b2, but the actual stop is 0.78, at first I didn't understand why 0.78 until I realize that is the high of b3, it looks like when the trade is executed at b2, does it assume that b2 is already closed so it goes to b3 to exit the trade?

Same thing happens to take profit, some stop price is way higher than expected.

I also tried to explicitly set stop_limit_price and stop_exit_price, but it's the same result.

Trade record:
```
    type    symbol          entry_date           exit_date  entry  exit      shares    pnl  return_pct  agg_pnl  bars  pnl_per_bar    stop 
7   long  POWRUSDT 2024-01-07 08:00:00 2024-01-07 09:00:00   1.11  0.78   89.950471 -29.69      -29.71   -34.70     1       -29.69    loss
```

How does it work exactly? And how can I make it work like what I expected (that it stops at 1.07 on b2)?

Thanks.

**Comment by edtechre** [comment]
Hi @tsunamilx,

The stop will execute on the same bar it is triggered. Based on the trade log, it looks like the position was opened at 8:00, and then exited at 9:00 due to the 10% stop loss in place. 

The stop is triggered because the price dropped more than 3% going from b2 to b3. The high price is used since the following bar b3 dropped more than the 3% stop value, so the high price is the closest recorded value to use for the exit. See:

https://github.com/edtechre/pybroker/blob/master/src/pybroker/portfolio.py#L1264

Let me know if you have ant other questions!

**Comment by tsunamilx** [comment]
> This is because the order was executed on that bar given all of the OHLC information, and the stop would need to take place after that.
So it is what I thought in the first place: "it looks like when the trade is executed at b2, does it assume that b2 is already closed so it goes to b3 to exit the trade?"

My process is like this:
b1: opens at 07:00, closes at 08:00, my signal appears at b1 close, and I place the order, I expect the order to be executed at b2 open, and the 3% stop loss should be triggered in the middle of b2.
b2: opens at 08:00, closes at 09:00, pybroker executes the order at b2, but it seems it thought b2 has closed, so it went to b3 to execute the stop

Am I doing it wrong? How can I  make it trigger the stop in the middle of b2?

Thanks.

**Comment by tsunamilx** [comment]
@edtechre please help ↑↑↑

**Comment by edtechre** [comment]
Hi @tsunamilx,

The stop is triggered because going from b2 -> b3 results in a > 3% drop. However, b3 dropped more than 3% as indicated by the high price, which is used for the fill price instead.

There is no "middle" of b2. The stop can only trigger after the discrete time step of b2 has been completed, since the position was opened on the same bar.
