### ISSUE TITLE
Is it possible to add more metrics?

### ISSUE THREAD

**Issue by none2003** [edtechre/pybroker#21]
Hi edtechre,

Is it possible to add more metrics? Like following:

Buy & Hold Return [%]              293.941538 
Return (Ann.) [%]                   20.080276
Volatility (Ann.) [%]               18.147456
Sortino Ratio                        2.091836
Calmar Ratio                         1.127568

**Comment by edtechre** [comment]
Thanks for the suggestion, yes I can add these.

Can you give an example for the calculation of Buy & Hold Return?

**Comment by none2003** [comment]
What I know about Buy & Hold is, for Long, buy the instrument/symbol with all cash at the start_date, hold it still, and close the position at the end_date of backtest.

**Comment by edtechre** [comment]
For Buy and Hold, you can achieve the same behavior by setting [StrategyConfig#exit_on_last_bar](https://www.pybroker.com/en/latest/reference/pybroker.config.html#pybroker.config.StrategyConfig.exit_on_last_bar) to True.

**Comment by edtechre** [comment]
Hi @none2003,

These metrics have been committed to the [dev branch](https://github.com/edtechre/pybroker/tree/dev). Because PyBroker is timeframe agnostic, you will need to set the [annual_bars](https://www.pybroker.com/en/dev/reference/pybroker.config.html#pybroker.config.StrategyConfig.annual_bars) config option to enable these metrics.
