### ISSUE TITLE
Some questions about intraday trading

### ISSUE THREAD

**Issue by pennymax** [edtechre/pybroker#44]
Hi, @edtechre,

I have several intraday related scenarios but don't know how to implement in pybroker. It's appreciated if you could give some suggestions.

Scenario 1: 
  1. Day1, got the signal to long BTC; buy order scheduled to be filled on Day2
  2. Day2, buy order filled; and got the signal to short BTC in Day3
  3. Day3, expect to close the long position then open a short position. How to achieve this in a right way?

Scenario 2:
  1. Day1,  got the signal to long BTC; and set the stop loss pct as 2
  2. Day2, buy order filled with OPEN price. BTC price dropped 5%. Expect to have the stop order filled in Day2 rather than Day3. (because in Day3, we may get bigger loss than 5%)    How to achieve this in a right way?

Thanks

**Comment by edtechre** [comment]
Hi @pennymax,

> Day3, expect to close the long position then open a short position. How to achieve this in a right way?

You can set ``ctx.sell_shares`` equal to the number of shares in the long position + number of shares to short. That will have the effect of selling your long shares, and then shorting the remaining shares.

> Day2, buy order filled with OPEN price. BTC price dropped 5%. Expect to have the stop order filled in Day2 rather than Day3. (because in Day3, we may get bigger loss than 5%) How to achieve this in a right way?

The stop cannot be filled on the same bar that the order was filled. However, setting [ctx.stop_loss_pct](https://www.pybroker.com/en/latest/reference/pybroker.context.html#pybroker.context.ExecContext.stop_loss_pct) will limit your loss to 5%. The only exception occurs when the -5% price falls outside the LOW-HIGH range of DAY 3; in such instances, the HIGH price will be used to fill the stop. You can also instead use intraday bars instead of daily bars to more accurately simulate an intraday stop.

Let me know if that helps!

**Comment by pennymax** [comment]
Yes, it works! Thanks for your explanation!
